version: "3"

services:
  arca_app:
    build: .
    container_name: arca_app
    volumes:
      - .:/var/www
    # ports:
    #   - "8000:8000"
    networks:
      - arca_network
    depends_on:
      - database

  nginx:
    build: docker/nginx
    container_name: arca_app_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - arca_network
    depends_on:
      - arca_app   
  
  database:
    container_name: arca_app_database
    ports:
      - "3307:3306"
    volumes:
      - arca_mysql:/var/lib/mysql
    image: mysql:8.0.31
    environment:
      - MYSQL_DATABASE=arca_database
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - arca_network

networks:
  arca_network:
    driver: bridge

volumes:
  arca_mysql:
    driver: local
