controllers:
    resource: ../src/Controller/
    type: attribute

app_logout:
    path: /logout
    methods: GET

# app_front_page:
#     controller: App\Controller\BusinessController::frontPage
#     path: /
#     methods: GET
