controllers:
    resource: ../src/Controller/
    type: attribute

app_logout:
    path: /logout
    methods: GET

app_user_index:
    controller: App\Controller\UserController::index
    path: /user
    methods: GET
